import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black antialiased`}
        style={{ fontFamily: "var(--font-satoshi), sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}
